#PBS -S /bin/sh
#PBS -M user@hpc.jcu.edu.au
#PBS -m n
#PBS -j oe
#PBS -l ncpus=1
#PBS -l pmem=1gb
#PBS -l walltime=02:00:00

pypi_install=false

if [ "$pypi_install" = true ] ; then
    source activate dartqc
fi

source ~/.bashrc

cd $PBS_O_WORKDIR

echo $PATH

if [ ! "$command" ]
    then
	    echo -e "Error: script must be supplied with a command"
	    exit 1
	else
    	echo "$command"
	    eval "$command"
fi

exit 0
